// <auto-generated />
using System;
using MediaBedrock.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaBedrock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250503150849_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MediaBedrock.Domain.JobAssets.JobAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobStateMachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobStateMachineId");

                    b.ToTable("JobAssets");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobTemplates.JobTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobTemplates");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobTemplates.JobTemplateStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("JobTemplateSteps");
                });

            modelBuilder.Entity("MediaBedrock.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("MediaBedrock.Domain.Jobs.Steps.JobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobSteps");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobsStateMachine.JobStateMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobsStateMachines");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobsStateMachine.JobStepStateMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobStateMachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobStateMachineId");

                    b.ToTable("JobStepStateMachines");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobAssets.JobAsset", b =>
                {
                    b.HasOne("MediaBedrock.Domain.JobsStateMachine.JobStateMachine", "JobStateMachine")
                        .WithMany("AssetsPool")
                        .HasForeignKey("JobStateMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MediaBedrock.Sdk.Processors.MediaInformation", "MediaInformation", b1 =>
                        {
                            b1.Property<Guid>("JobAssetId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("JobAssetId");

                            b1.ToTable("JobAssets");

                            b1.WithOwner()
                                .HasForeignKey("JobAssetId");
                        });

                    b.Navigation("JobStateMachine");

                    b.Navigation("MediaInformation");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobTemplates.JobTemplate", b =>
                {
                    b.OwnsMany("MediaBedrock.Domain.JobTemplates.JobTemplateInput", "Inputs", b1 =>
                        {
                            b1.Property<Guid>("JobTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobTemplateId", "__synthesizedOrdinal");

                            b1.ToTable("JobTemplates");

                            b1.ToJson("Inputs");

                            b1.WithOwner()
                                .HasForeignKey("JobTemplateId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.JobTemplates.JobTemplateOutput", "Outputs", b1 =>
                        {
                            b1.Property<Guid>("JobTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobTemplateId", "__synthesizedOrdinal");

                            b1.ToTable("JobTemplates");

                            b1.ToJson("Outputs");

                            b1.WithOwner()
                                .HasForeignKey("JobTemplateId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.JobTemplates.JobTemplateProperty", "Properties", b1 =>
                        {
                            b1.Property<Guid>("JobTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DefaultValue")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobTemplateId", "__synthesizedOrdinal");

                            b1.ToTable("JobTemplates");

                            b1.ToJson("Properties");

                            b1.WithOwner()
                                .HasForeignKey("JobTemplateId");
                        });

                    b.Navigation("Inputs");

                    b.Navigation("Outputs");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobTemplates.JobTemplateStep", b =>
                {
                    b.HasOne("MediaBedrock.Domain.JobTemplates.JobTemplate", "Template")
                        .WithMany("Steps")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MediaBedrock.Domain.JobTemplates.JobTemplateStepInput", "Inputs", b1 =>
                        {
                            b1.Property<Guid>("JobTemplateStepId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobTemplateStepId", "__synthesizedOrdinal");

                            b1.ToTable("JobTemplateSteps");

                            b1.ToJson("Inputs");

                            b1.WithOwner()
                                .HasForeignKey("JobTemplateStepId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.JobTemplates.JobTemplateStepOutput", "Outputs", b1 =>
                        {
                            b1.Property<Guid>("JobTemplateStepId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Destination")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobTemplateStepId", "__synthesizedOrdinal");

                            b1.ToTable("JobTemplateSteps");

                            b1.ToJson("Outputs");

                            b1.WithOwner()
                                .HasForeignKey("JobTemplateStepId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.JobTemplates.JobTemplateStepProperty", "Properties", b1 =>
                        {
                            b1.Property<Guid>("JobTemplateStepId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobTemplateStepId", "__synthesizedOrdinal");

                            b1.ToTable("JobTemplateSteps");

                            b1.ToJson("Properties");

                            b1.WithOwner()
                                .HasForeignKey("JobTemplateStepId");
                        });

                    b.Navigation("Inputs");

                    b.Navigation("Outputs");

                    b.Navigation("Properties");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaBedrock.Domain.Jobs.Job", b =>
                {
                    b.HasOne("MediaBedrock.Domain.JobTemplates.JobTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("MediaBedrock.Domain.Jobs.JobInput", "Inputs", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Uri")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobId", "__synthesizedOrdinal");

                            b1.ToTable("Jobs");

                            b1.ToJson("Inputs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.Jobs.JobOutput", "Outputs", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobId", "__synthesizedOrdinal");

                            b1.ToTable("Jobs");

                            b1.ToJson("Outputs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Inputs");

                    b.Navigation("Outputs");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaBedrock.Domain.Jobs.Steps.JobStep", b =>
                {
                    b.HasOne("MediaBedrock.Domain.Jobs.Job", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MediaBedrock.Domain.Jobs.Steps.JobStepInput", "Inputs", b1 =>
                        {
                            b1.Property<Guid>("JobStepId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AssetName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobStepId", "__synthesizedOrdinal");

                            b1.ToTable("JobSteps");

                            b1.ToJson("Inputs");

                            b1.WithOwner()
                                .HasForeignKey("JobStepId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.Jobs.Steps.JobStepOutput", "Outputs", b1 =>
                        {
                            b1.Property<Guid>("JobStepId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AssetName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobStepId", "__synthesizedOrdinal");

                            b1.ToTable("JobSteps");

                            b1.ToJson("Outputs");

                            b1.WithOwner()
                                .HasForeignKey("JobStepId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.Jobs.Steps.JobStepProperty", "Properties", b1 =>
                        {
                            b1.Property<Guid>("JobStepId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("JobStepId", "__synthesizedOrdinal");

                            b1.ToTable("JobSteps");

                            b1.ToJson("Properties");

                            b1.WithOwner()
                                .HasForeignKey("JobStepId");
                        });

                    b.Navigation("Inputs");

                    b.Navigation("Job");

                    b.Navigation("Outputs");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobsStateMachine.JobStateMachine", b =>
                {
                    b.HasOne("MediaBedrock.Domain.Jobs.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobsStateMachine.JobStepStateMachine", b =>
                {
                    b.HasOne("MediaBedrock.Domain.JobsStateMachine.JobStateMachine", "JobStateMachine")
                        .WithMany("StepsStateMachines")
                        .HasForeignKey("JobStateMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MediaBedrock.Domain.JobsStateMachine.JobStepExecutionError", "ExecutionError", b1 =>
                        {
                            b1.Property<Guid>("JobStepStateMachineId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Message")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.HasKey("JobStepStateMachineId");

                            b1.ToTable("JobStepStateMachines");

                            b1.WithOwner()
                                .HasForeignKey("JobStepStateMachineId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.Jobs.Steps.JobStepInput", "StepInputs", b1 =>
                        {
                            b1.Property<Guid>("JobStepStateMachineId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AssetName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobStepStateMachineId", "__synthesizedOrdinal");

                            b1.ToTable("JobStepStateMachines");

                            b1.ToJson("StepInputs");

                            b1.WithOwner()
                                .HasForeignKey("JobStepStateMachineId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.Jobs.Steps.JobStepOutput", "StepOutputs", b1 =>
                        {
                            b1.Property<Guid>("JobStepStateMachineId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AssetName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobStepStateMachineId", "__synthesizedOrdinal");

                            b1.ToTable("JobStepStateMachines");

                            b1.ToJson("StepOutputs");

                            b1.WithOwner()
                                .HasForeignKey("JobStepStateMachineId");
                        });

                    b.OwnsMany("MediaBedrock.Domain.Jobs.Steps.JobStepProperty", "StepProperties", b1 =>
                        {
                            b1.Property<Guid>("JobStepStateMachineId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("JobStepStateMachineId", "__synthesizedOrdinal");

                            b1.ToTable("JobStepStateMachines");

                            b1.ToJson("StepProperties");

                            b1.WithOwner()
                                .HasForeignKey("JobStepStateMachineId");
                        });

                    b.Navigation("ExecutionError");

                    b.Navigation("JobStateMachine");

                    b.Navigation("StepInputs");

                    b.Navigation("StepOutputs");

                    b.Navigation("StepProperties");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobTemplates.JobTemplate", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MediaBedrock.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MediaBedrock.Domain.JobsStateMachine.JobStateMachine", b =>
                {
                    b.Navigation("AssetsPool");

                    b.Navigation("StepsStateMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
